# Site settings
title: My Midnight Muse
header-img: img/home-bg.jpg
email: khoslastuti16@gmail.com
copyright_name: My Midnight Muse
description: "Pens, Brushes, and all Heart."
baseurl: ""
author: "Stuti Khosla"
url: "http://mymidnightmuse.in"
github_username:  stuti1995/dory-blog/
facebook_username:  stuti.khosla
email_username:  khoslastuti16@gmail.com 
developer_url: "https://abhinavagrawal.in"
developer: "Abhinav Agrawal"

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: "UA-52121429-5"
disqus-shortname: mymidnidhtmuse

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
